language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t smritik693/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true smritik693/docker-react npm run test    

